{ nixpkgs, pkgs, rnsModule, rnsProfile }:

let
  inherit (nixpkgs) lib;
  mkConfig = extra: (lib.nixosSystem {
    modules = [
      rnsModule
      rnsProfile
      {
        nixpkgs.pkgs = nixpkgs.legacyPackages.x86_64-linux;
        system.stateVersion = "26.05";
        # Config generation does not execute the daemon or build its Rust package.
        lattice.rns-server.package = nixpkgs.legacyPackages.x86_64-linux.hello;
      }
      extra
    ];
  }).config;
  failures = config: map (item: item.message) (lib.filter
    (item: !item.assertion && lib.hasPrefix "lattice.rns-server.interfaces." item.message)
    config.assertions);
  base = mkConfig { };
  client = mkConfig {
    lattice.rns-server.interfaces = {
      "TCP Server".enabled = false;
      "TCP Uplink" = { enabled = true; target_host = "entry.example.net"; };
    };
  };
  custom = mkConfig {
    lattice.rns-server.interfaces = {
      "TCP Server" = {
        listen_ip = "127.0.0.1";
        listen_port = 14242;
        max_connections = 8;
        openFirewall = true;
      };
      "TCP Uplink" = { enabled = true; target_host = "[::1]"; target_port = 14243; };
      "Disabled TCP" = {
        type = "TCPServerInterface";
        enabled = false;
        listen_port = 14244;
        openFirewall = true;
      };
    };
  };
  invalid = interface: mkConfig {
    lattice.rns-server.interfaces."Invalid TCP" = interface;
  };
  accepts = interface: failures (invalid interface) == [ ];
  badClient = { type = "TCPClientInterface"; target_port = 4242; };
  badServer = { type = "TCPServerInterface"; listen_ip = "127.0.0.1"; };
  validClient = badClient // { target_host = "entry.example.net"; };
  validServer = badServer // { listen_port = 4242; };
  evaluates = interface: (builtins.tryEval (builtins.deepSeq
    (invalid interface).lattice.rns-server.interfaces."Invalid TCP" true)).success;
  # Use the exact generated bytes, with the test runner's platform for writeText.
  # This permits running the same ConfigObj check on macOS and on Linux CI.
  baseFile = pkgs.writeText "rns-profile-config" base.lattice.rns-server.configFile.text;
  clientFile = pkgs.writeText "rns-client-config" client.lattice.rns-server.configFile.text;
  customFile = pkgs.writeText "rns-custom-config" custom.lattice.rns-server.configFile.text;
in
assert failures base == [ ];
assert failures client == [ ];
assert failures custom == [ ];
assert base.networking.firewall.allowedTCPPorts == [ ];
assert client.networking.firewall.allowedTCPPorts == [ ];
assert custom.networking.firewall.allowedTCPPorts == [ 14242 ];
assert (mkConfig { lattice.rns-server.enable = false; }).networking.firewall.allowedTCPPorts == [ ];
assert !accepts badClient;
assert !accepts (validClient // { target_port = null; });
assert !accepts badServer;
assert !accepts (validServer // { listen_ip = null; });
assert accepts (badClient // { enabled = false; });
assert !accepts (validClient // { openFirewall = true; });
assert !accepts (validServer // { extraConfig.listen_port = 4243; });
assert !accepts (validServer // { address = "127.0.0.1:4243"; });
assert !evaluates (validClient // { target_port = 65536; });
assert !evaluates (validClient // { target_port = 0; });
assert !evaluates (validServer // { listen_port = 0; });
assert !evaluates (validClient // { target_host = ""; });
assert !evaluates (validClient // { target_host = "host\nlisten_port = 9999"; });
assert !evaluates (validServer // { max_connections = 0; });
pkgs.runCommand "rns-tcp-config-check" {
  nativeBuildInputs = [ (pkgs.python3.withPackages (python: [ python.configobj ])) ];
} ''
  python ${./rns-tcp-config.py} \
    ${baseFile} \
    ${clientFile} \
    ${customFile}
  mkdir -p "$out"
  cp ${baseFile} "$out/profile.config"
  cp ${clientFile} "$out/client.config"
  cp ${customFile} "$out/custom.config"
''
