name: Docs

on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"

  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "docs/**"

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  link-check:
    name: Link check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check links
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          lycheeVersion: v0.24.2
          args: --no-progress --format detailed .
          fail: true
