name: Checks

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ runner.arch }}-

      - name: Build and check flake
        run: nix flake check --print-build-logs

  lychee:
    name: Link check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Lychee link checker
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          lycheeVersion: v0.24.2
          args: --no-progress --format detailed .
          fail: true
