name: Nix

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"

  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**"

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Nix cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ runner.arch }}-

      - name: Flake check
        run: nix flake check --print-build-logs
